### ISSUE TITLE
trouble starting out

### ISSUE THREAD

**Issue by robbiemu** [dondido/express-es6-template-engine#2]
edit: solution: simply add --harmony to the runtime params for node.js — my bad. :)

I'm trying to just plug this into a node.js project in intellij idea. I pruned  the old templating engine and replaced it as the view engine  like

### app.js
```
var es6Renderer = require('express-es6-template-engine');
...
app.engine('html', es6Renderer);

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'html');
```

and I set the project to use ecmascript 6 instead of default javascript. and this is in a node v.4.13.1

I am getting this error:
```
"C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.1\bin\runnerw.exe" "C:\Program Files (x86)\node.js\node.exe" bin\www
c:\Users\RobertoTomás\Desktop\nodes\intellijNodeExpressBase\node_modules\express-es6-template-engine\es6-renderer.js:5
      ...keyList,
      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (c:\Users\RobertoTomás\Desktop\nodes\intellijNodeExpressBase\app.js:2:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

Process finished with exit code 1
```

Which looks to me like it is not using ecmascript6 .. but I know that it is... in that app.js file I can  `class SomeClass {}` and not get a warning.

**Comment by dondido** [comment]
This issue is more likely due to version incompatibility, The engine requires Node version 4.0 or higher. You can tell the version by executing `nodejs -v` in the terminal.
